---
title: "WindsAndTemps"
author: "Charlie"
date: "3/25/2020"
output:
  pdf_document: default
  html_document:
    df_print: paged
  word_document: default
---

```{r echo=FALSE}
### Local links -- work if in RStudio Project
source(file="../scripts/reference.R");
weatherData = read.csv(file="../data/LansingWeather2016-NOAA.csv",
                       stringsAsFactors = FALSE);

avgTemp = weatherData$avgTemp;  # get the avgTemp column from the data frame

# create vector to hold change in temp values
changeTemp = vector(mode = "integer", length = nrow(weatherData));
changeTemp[1] = NA;  # there is no day before the first to calculate

#### Starting with the second day, calculate the change in temperatures
for(day in 2:nrow(weatherData))
{
  changeTemp[day] = avgTemp[day] - avgTemp[day-1];
}
weatherData$changeTemp = changeTemp;  # save vector as column in data frame
```

Text before Plot 1 ...

```{r echo=TRUE}
#### Plot the histogram of the change in temperature
plot1 = hist(changeTemp,
             main = "Daily change of average temperatures",
             xlab = "Change in Temperature (Fahrenheit)");
```


Text before Summary stats ...

```{r echo=TRUE, eval=FALSE}
#### Get some statistics on the change in tempeature values
cat("Summary statistics for the change in temperature:\n");
print(summary(changeTemp));  
```

```{r echo=FALSE, eval=TRUE}
#### number of days with winds from each direction
cat("\nNumber of days with prevailing winds from the cardinal directions:");
print(table(weatherData$windDir));
```


```{r echo=FALSE, eval=FALSE}
#### GGPlot: Create a box for each wind direction 
plot2 = ggplot(data=weatherData) +
  geom_boxplot(mapping=aes(x=windDir, y=changeTemp), 
               na.rm=TRUE) +
  theme_bw() +
  scale_x_discrete(limits=c("North", "East", "South", "West")) +
  labs(title = "Change in Temperature by Prevailing Wind Direction",
       subtitle = "Lansing, Michigan: 2016",
       x = "Wind Direction",
       y = "Change in Temperature (\U00B0 F)");
plot(plot2);
```


```{r echo=FALSE}
plot3 = ggplot(data=weatherData) +
  geom_boxplot(mapping=aes(x=windSpeedLevel, y=changeTemp), 
               na.rm=TRUE,
               color="gray20",
               fill="gray70") +
  theme_bw() +
  scale_x_discrete(limits=c("Low", "Medium", "High")) +
  facet_grid(facets=.~factor(windDir,
                      levels=c("North", "East", "South", "West"))) +
  labs(title = "Change in Temperature by Wind Direction and Speed",
       subtitle = "Lansing, Michigan: 2016",
       x = "Wind Speed levels within each Wind Direction",
       y = "Change in Temperature (\U00B0 F)");
plot(plot3);
```

```{r echo=TRUE, eval=TRUE}
#### Get some statistics on the change in tempeature values
cat("Summary statistics for the average temperature:\n");
print(summary(avgTemp));

#### avgTemp histogram
plot4 = hist(avgTemp);
```

End of document text